CREATE TABLE IF NOT EXISTS "flasks_ref" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"original_flask_id" INTEGER NOT NULL,
	"new_flask_id" INTEGER NOT NULL,
	"flask_ref_type_id" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "flask_ref_type" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "boxes" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT NOT NULL,
	"remarks" TEXT,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "boxes" IS 'Once box is used in box_content_headers the name cannot be updated.';
CREATE INDEX "boxes_index_0"
ON "boxes" ("name");

CREATE TABLE IF NOT EXISTS "box_content_headers" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"box_id" INTEGER NOT NULL,
	"destination_text" TEXT,
	"ready_at" TIMESTAMPTZ,
	"returned_at" TIMESTAMPTZ,
	"remarks" TEXT,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "box_content_headers" IS 'Only 1 instance(row) of box_id and ready_at is allowed. returned_at can only be filled when ready_at is filled.
';


CREATE TABLE IF NOT EXISTS "flasks" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT NOT NULL,
	"remarks" TEXT,
	"broken_at" TIMESTAMPTZ,
	"Low_pressure_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "flasks" IS 'Once flask is used in box_content_lines or flasks_ref the name cannot be updated';
CREATE INDEX "flasks_index_0"
ON "flasks" ("name");

CREATE TABLE IF NOT EXISTS "box_content_lines" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"box_content_header_id" INTEGER NOT NULL,
	"flask_id" INTEGER NOT NULL,
	"remarks" TEXT,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "box_content_lines" IS 'box_content_header_id and flask_id should be unique';

ALTER TABLE "flasks"
ADD FOREIGN KEY("id") REFERENCES "flasks_ref"("new_flask_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "flasks"
ADD FOREIGN KEY("id") REFERENCES "flasks_ref"("original_flask_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "flask_ref_type"
ADD FOREIGN KEY("id") REFERENCES "flasks_ref"("flask_ref_type_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "boxes"
ADD FOREIGN KEY("id") REFERENCES "box_content_headers"("box_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "box_content_headers"
ADD FOREIGN KEY("id") REFERENCES "box_content_lines"("box_content_header_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "flasks"
ADD FOREIGN KEY("id") REFERENCES "box_content_lines"("flask_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;