CREATE TABLE IF NOT EXISTS "flasks_ref" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"original_flask_id" INTEGER NOT NULL,
	"new_flask_id" INTEGER NOT NULL,
	"flask_ref_type_id" INTEGER,
	"created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	"created_by" TEXT,
	"updated_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	"updated_by" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "flask_ref_type" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT,
	"created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	"created_by" TEXT,
	"updated_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	"updated_by" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "boxes" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT NOT NULL,
	"remarks" TEXT,
	"created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	"created_by" TEXT,
	"updated_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	"updated_by" TEXT,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "boxes" IS 'Once box is used in box_content_headers the name cannot be updated.';
CREATE INDEX "boxes_index_0"
ON "boxes" ("name");

CREATE TABLE IF NOT EXISTS "box_content_headers" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"box_id" INTEGER NOT NULL,
	"destination_text" TEXT,
	"ready_at" TIMESTAMPTZ,
	"returned_at" TIMESTAMPTZ,
	"remarks" TEXT,
	"created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	"created_by" TEXT,
	"updated_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	"updated_by" TEXT,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "box_content_headers" IS 'Only 1 instance(row) of box_id and ready_at is allowed. returned_at can only be filled when ready_at is filled.
';


CREATE TABLE IF NOT EXISTS "flasks" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT NOT NULL,
	"remarks" TEXT,
	"broken_at" TIMESTAMPTZ,
	"Low_pressure_at" TIMESTAMPTZ,
	"created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	"created_by" TEXT,
	"updated_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	"updated_by" TEXT,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "flasks" IS 'Once flask is used in box_content_lines or flasks_ref the name cannot be updated';
CREATE INDEX "flasks_index_0"
ON "flasks" ("name");

CREATE TABLE IF NOT EXISTS "box_content_lines" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"box_content_header_id" INTEGER NOT NULL,
	"flask_id" INTEGER NOT NULL,
	"remarks" TEXT,
	"created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	"created_by" TEXT,
	"updated_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	"updated_by" TEXT,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "box_content_lines" IS 'box_content_header_id and flask_id should be unique';

ALTER TABLE "flasks_ref"
ADD CONSTRAINT "fk_flasks_ref_2"
FOREIGN KEY("new_flask_id") REFERENCES "flasks"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "flasks_ref"
ADD CONSTRAINT "fk_flasks_ref_1"
FOREIGN KEY("original_flask_id") REFERENCES "flasks"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "flasks_ref"
ADD CONSTRAINT "fk_flask_ref_3"
FOREIGN KEY("flask_ref_type_id") REFERENCES "flask_ref_type"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "box_content_headers"
ADD CONSTRAINT "fk_flasks_boxes_2"
FOREIGN KEY("box_id") REFERENCES "boxes"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "box_content_lines"
ADD CONSTRAINT "fk_box_content_lines_1"
FOREIGN KEY("box_content_header_id") REFERENCES "box_content_headers"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "box_content_lines"
ADD CONSTRAINT "fk_box_content_lines_2"
FOREIGN KEY("flask_id") REFERENCES "flasks"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Trigger function to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers for each table
CREATE TRIGGER update_flasks_ref_updated_at
    BEFORE UPDATE ON flasks_ref
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_flask_ref_type_updated_at
    BEFORE UPDATE ON flask_ref_type
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_boxes_updated_at
    BEFORE UPDATE ON boxes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_box_content_headers_updated_at
    BEFORE UPDATE ON box_content_headers
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_flasks_updated_at
    BEFORE UPDATE ON flasks
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_box_content_lines_updated_at
    BEFORE UPDATE ON box_content_lines
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();