-- Migration 0005: Add flasks history tracking
-- Purpose: Track all changes to flasks table for audit trail
-- This enables tracking of multiple low pressure events, status changes, and complete flask lifecycle

-- Create history table
CREATE TABLE flasks_hist (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    flask_id INTEGER NOT NULL,

    -- Old and new values for tracked fields
    old_name TEXT,
    new_name TEXT,
    old_remarks TEXT,
    new_remarks TEXT,
    old_broken_at TIMESTAMPTZ,
    new_broken_at TIMESTAMPTZ,
    old_low_pressure_at TIMESTAMPTZ,
    new_low_pressure_at TIMESTAMPTZ,

    -- Audit metadata
    operation TEXT NOT NULL CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE')),
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_by TEXT REFERENCES "user"(id) ON DELETE SET NULL
);

-- Indexes for performance
CREATE INDEX idx_flasks_hist_flask_id ON flasks_hist(flask_id);
CREATE INDEX idx_flasks_hist_changed_at ON flasks_hist(changed_at);
CREATE INDEX idx_flasks_hist_operation ON flasks_hist(operation);

-- Comment on table
COMMENT ON TABLE flasks_hist IS 'Audit history for all changes to flasks table. Captures old and new values for tracked fields.';
COMMENT ON COLUMN flasks_hist.flask_id IS 'Reference to flasks.id (no FK constraint to allow history retention even if flask is deleted)';
COMMENT ON COLUMN flasks_hist.operation IS 'Type of operation: INSERT, UPDATE, or DELETE';
COMMENT ON COLUMN flasks_hist.changed_at IS 'Timestamp when the change occurred';
COMMENT ON COLUMN flasks_hist.changed_by IS 'User who made the change (from created_user_id for INSERT, updated_user_id for UPDATE)';

-- Trigger function to log flask changes
CREATE OR REPLACE FUNCTION log_flask_changes()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        -- Log initial flask creation
        INSERT INTO flasks_hist (
            flask_id,
            new_name,
            new_remarks,
            new_broken_at,
            new_low_pressure_at,
            operation,
            changed_at,
            changed_by
        ) VALUES (
            NEW.id,
            NEW.name,
            NEW.remarks,
            NEW.broken_at,
            NEW.low_pressure_at,
            'INSERT',
            CURRENT_TIMESTAMP,
            NEW.created_user_id
        );
        RETURN NEW;

    ELSIF (TG_OP = 'UPDATE') THEN
        -- Only log if tracked fields actually changed
        IF (OLD.name IS DISTINCT FROM NEW.name OR
            OLD.remarks IS DISTINCT FROM NEW.remarks OR
            OLD.broken_at IS DISTINCT FROM NEW.broken_at OR
            OLD.low_pressure_at IS DISTINCT FROM NEW.low_pressure_at) THEN

            INSERT INTO flasks_hist (
                flask_id,
                old_name,
                new_name,
                old_remarks,
                new_remarks,
                old_broken_at,
                new_broken_at,
                old_low_pressure_at,
                new_low_pressure_at,
                operation,
                changed_at,
                changed_by
            ) VALUES (
                NEW.id,
                OLD.name,
                NEW.name,
                OLD.remarks,
                NEW.remarks,
                OLD.broken_at,
                NEW.broken_at,
                OLD.low_pressure_at,
                NEW.low_pressure_at,
                'UPDATE',
                CURRENT_TIMESTAMP,
                NEW.updated_user_id
            );
        END IF;
        RETURN NEW;

    ELSIF (TG_OP = 'DELETE') THEN
        -- Log flask deletion (captures final state)
        INSERT INTO flasks_hist (
            flask_id,
            old_name,
            old_remarks,
            old_broken_at,
            old_low_pressure_at,
            operation,
            changed_at,
            changed_by
        ) VALUES (
            OLD.id,
            OLD.name,
            OLD.remarks,
            OLD.broken_at,
            OLD.low_pressure_at,
            'DELETE',
            CURRENT_TIMESTAMP,
            NULL  -- Can't capture who deleted from trigger context
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Comment on function
COMMENT ON FUNCTION log_flask_changes() IS 'Trigger function that automatically logs all INSERT, UPDATE, and DELETE operations on the flasks table to flasks_hist';

-- Create triggers
CREATE TRIGGER flasks_insert_history
AFTER INSERT ON flasks
FOR EACH ROW
EXECUTE FUNCTION log_flask_changes();

CREATE TRIGGER flasks_update_history
AFTER UPDATE ON flasks
FOR EACH ROW
EXECUTE FUNCTION log_flask_changes();

CREATE TRIGGER flasks_delete_history
AFTER DELETE ON flasks
FOR EACH ROW
EXECUTE FUNCTION log_flask_changes();

-- Optional: Populate history for existing flasks (one-time migration)
-- This creates an initial snapshot of all existing flasks
INSERT INTO flasks_hist (
    flask_id,
    new_name,
    new_remarks,
    new_broken_at,
    new_low_pressure_at,
    operation,
    changed_at,
    changed_by
)
SELECT
    id,
    name,
    remarks,
    broken_at,
    low_pressure_at,
    'INSERT',
    created_at,
    created_user_id
FROM flasks;

-- Add comment to confirm migration completion
COMMENT ON TABLE flasks_hist IS 'Audit history for all changes to flasks table. Captures old and new values for tracked fields. Migration 0005 applied.';
