-- Migration 0008: Refactor low pressure tracking to dedicated events table
-- Purpose: Replace single low_pressure_at timestamp with separate events table
-- This allows tracking multiple low pressure events per flask
-- Also removes flasks_hist table in favor of simpler tracking approach

-- Step 1: Create new flask_low_pressure_events table
CREATE TABLE flask_low_pressure_events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    flask_id INTEGER NOT NULL,
    low_pressure_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_flask_low_pressure_events_1
        FOREIGN KEY (flask_id) REFERENCES flasks(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

COMMENT ON TABLE flask_low_pressure_events IS 'Tracks low pressure events for flasks. Each row represents a separate low pressure occurrence.';
COMMENT ON COLUMN flask_low_pressure_events.flask_id IS 'Reference to the flask that experienced low pressure';
COMMENT ON COLUMN flask_low_pressure_events.low_pressure_at IS 'Timestamp when the flask was marked as low pressure';

-- Step 2: Migrate existing low_pressure_at data from flasks table
-- Only migrate flasks that have a low_pressure_at value
INSERT INTO flask_low_pressure_events (flask_id, low_pressure_at)
SELECT
    id,
    low_pressure_at  -- Keep as TIMESTAMPTZ
FROM flasks
WHERE low_pressure_at IS NOT NULL;

-- Step 3: Drop triggers on flasks table (created in migration 0005)
DROP TRIGGER IF EXISTS flasks_delete_history ON flasks;
DROP TRIGGER IF EXISTS flasks_update_history ON flasks;
DROP TRIGGER IF EXISTS flasks_insert_history ON flasks;

-- Step 4: Drop trigger function (created in migration 0005)
DROP FUNCTION IF EXISTS log_flask_changes();

-- Step 5: Drop flasks_hist table (created in migration 0005)
-- This will cascade drop the foreign key constraint to user table
DROP TABLE IF EXISTS flasks_hist;

-- Step 6: Drop low_pressure_at column from flasks table
ALTER TABLE flasks DROP COLUMN IF EXISTS low_pressure_at;

-- Add comment to confirm migration completion
COMMENT ON TABLE flask_low_pressure_events IS 'Tracks low pressure events for flasks. Each row represents a separate low pressure occurrence. Migration 0008 applied.';
