Table flask_ref_type [headercolor: #175e7a] {
	id integer [ pk, increment, not null, unique ]
	name text [ not null ]
}

Table boxes [headercolor: #175e7a] {
	id integer [ pk, increment, not null, unique ]
	name text [ not null ]
	remarks text

	indexes {
		(name) [ name: 'boxes_index_0' ]
	}

	Note: 'Once box is used in box_content_headers the name cannot be updated.'
}

Table box_content_headers [headercolor: #175e7a] {
	id integer [ pk, increment, not null, unique ]
	box_id integer [ not null ]
	destination_text text
	ready_at timestamptz
	returned_at timestamptz
	remarks text

	Note: '''Only 1 instance(row) of box_id and ready_at is allowed. returned_at can only be filled when ready_at is filled.
'''
}

Table flasks [headercolor: #175e7a] {
	id integer [ pk, increment, not null, unique ]
	name text [ not null ]
	remarks text
	broken_at timestamptz

	indexes {
		(name) [ name: 'flasks_index_0' ]
	}

	Note: 'Once flask is used in box_content_lines or flasks_ref the name cannot be updated'
}

Table box_content_lines [headercolor: #175e7a] {
	id integer [ pk, increment, not null, unique ]
	box_content_header_id integer [ not null ]
	flask_id integer [ not null ]
	remarks text

	indexes {
		(box_content_header_id, flask_id) [ name: 'box_content_lines_unique_index_1', unique ]
	}

	Note: 'box_content_header_id and flask_id should be unique'
}

Table flask_low_pressure_events [headercolor: #175e7a] {
	id integer [ pk, increment, not null, unique ]
	flask_id integer [ not null ]
	low_pressure_at timestamptz [ not null ]
}

Table flasks_ref [headercolor: #175e7a] {
	id integer [ pk, increment, not null, unique ]
	original_flask_id integer [ not null ]
	new_flask_id integer [ not null ]
	flask_ref_type_id integer [ not null ]

	indexes {
		(original_flask_id, new_flask_id) [ name: 'flasks_ref_unique_index_1', unique ]
		(new_flask_id, flask_ref_type_id) [ name: 'flasks_ref_unique_index_2', unique ]
	}
}

Ref fk_box_content_lines_1 {
	box_content_headers.id < box_content_lines.box_content_header_id [ delete: no action, update: no action ]
}

Ref fk_box_content_lines_2 {
	flasks.id < box_content_lines.flask_id [ delete: no action, update: no action ]
}

Ref fk_flask_ref_3 {
	flask_ref_type.id < flasks_ref.flask_ref_type_id [ delete: no action, update: no action ]
}

Ref fk_flasks_ref_2 {
	flasks.id < flasks_ref.new_flask_id [ delete: no action, update: no action ]
}

Ref fk_flasks_ref_1 {
	flasks.id < flasks_ref.original_flask_id [ delete: no action, update: no action ]
}

Ref fk_flasks_boxes_2 {
	boxes.id < box_content_headers.box_id [ delete: no action, update: no action ]
}

Ref fk_flask_low_pressure_events_1 {
	flasks.id < flask_low_pressure_events.flask_id [ delete: no action, update: no action ]
}